networks:
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.40.0/25

services:
  poolapi:
    container_name: nflpoolapi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/cygnus/temp:/misc
    networks:
      t2_proxy:
        ipv4_address: 192.168.40.100
    hostname: poolapi
    ports:
      - 7000:7000
  
  poolsite:
    container_name: nflpoolsite
    build:
      context: ./nflpoolsite
      dockerfile: Dockerfile
    networks:
      t2_proxy:
        ipv4_address: 192.168.40.101
    hostname: poolsite
    ports:
      - 4000:4000
    depends_on:
      - poolapi
