networks:
  nfl_pool_proxy:
    name: nfl_pool_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.80.0/25

services:
  pooldb:
    container_name: nflpooldb
    image: couchbase:community-7.2.1
    networks:
      nfl_pool_proxy:
        ipv4_address: 192.168.80.100
    hostname: pooldb
    ports:
      - "8091-8096:8091-8096"
      - "11207-11211:11207-11211"
    volumes:
      - /mnt/ssd/docker/appdata/couchbase:/opt/couchbase/var
  poolapi:
    container_name: nflpoolapi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/cygnus/temp:/misc
    networks:
      nfl_pool_proxy:
        ipv4_address: 192.168.80.101
    hostname: poolapi
    ports:
      - 8083:8080
    depends_on:
      - pooldb

  poolsite:
    container_name: nflpoolsite
    build:
      context: ./nflpoolsite
      dockerfile: Dockerfile
    networks:
      nfl_pool_proxy:
        ipv4_address: 192.168.80.102
    hostname: poolsite
    ports:
      - 4000:4000
    depends_on:
      - poolapi